name: Build pza-pico-modbus-dio

on:
  push:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Cmake
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: 3.25.0
        ninjaVersion: 1.11.1

    - name: Create build dir
      working-directory: examples/pza-pico-modbus-dio
      run: >
        mkdir -p build

    - name: Build configuration
      working-directory: examples/pza-pico-modbus-dio/build
      run: >
        cmake
        ..

    - name: Make!
      working-directory: examples/pza-pico-modbus-dio/build
      run: >
        cmake
        --build
        .

    - run: ls -la examples/pza-pico-modbus-dio/build

    #- name: Store artifacts
    #  uses: actions/upload-artifact@v3
    #  with:
    #    name: build-pico
    #    path: examples/pza-pico-modbus-dio/build

